[package]
name = "gst-log-diff"
version = "0.1.0"
authors = ["Philippe Normand <philn@igalia.com>"]
edition = "2018"

[dependencies]
gst-log-parser = { git = "https://github.com/gdesmott/gst-log-parser.git" }
#gst-log-parser = { path = "../gst-log-parser" }
structopt = "0.2.16"
structopt-derive = "0.2.16"
difference = "2.0.0"
term = "0.5.2"
regex = "1.1.7"
